name: example
description: A new Flutter project to quickly test flutter_launcher_icons.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_yaml_plus: 
    git: 
      url: git@git.17usoft.com:mada-app/TCGroundFlutterWebsocket.git
      ref: 0.0.1
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_yaml_plus: 
    path: ../
flutter: 
  uses-material-design: true
