name: example
description: A new Flutter project to quickly test flutter_launcher_icons.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.3
  #保留注释
  flutter_tc_foundation:
    git:
      url: test
      ref: pay_1.0
      path: flutter_tc_foundation
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_yaml_plus: 
    path: ../
flutter: 
  uses-material-design: true
