versions:
  version1: &foundation_version pay_1.0
dependencies:
  flutter_tc_foundation: &flutter_tc_foundation
    path:
      ../flutter_tc_foundation
    git:
      url: test
      ref: *foundation_version
      path: flutter_tc_foundation