name: flutter_yaml_plus
description: pubspec.yaml增强.
version: 0.0.1
maintainer: Mark O'Sullivan (@MarkOSullivan94)
homepage: https://github.com/JDongKhan/flutter_yaml_plus.git
repository: https://github.com/JDongKhan/flutter_yaml_plus.git
issue_tracker: https://github.com/JDongKhan/flutter_yaml_plus.git/issues
dependencies: 
  args: ^2.3.2
  cli_util: ^0.4.0
  checked_yaml: ^2.0.2
  path: ^1.8.2
  yaml: ^3.1.1
  yaml_modify: ^1.0.1
  #test: 2
environment: 
  sdk: '>=2.18.0 <3.0.0'
dev_dependencies: 
  build_runner: ^2.3.3
  build_version: ^2.1.1
